#!/bin/bash

# Deploy N11 fixes to VPS and verify resolution
# This script handles the VPS deployment for N11 Sequelize warning investigation

echo "🚀 Deploying N11 fixes to VPS"
echo "=============================="

echo ""
echo "📋 What this deployment includes:"
echo "✅ Enhanced Trendyol network error handling"
echo "✅ N11 Sequelize warning investigation and verification"
echo "✅ Production enum value fixes"
echo "✅ Improved platform service retry logic"
echo ""

echo "🔧 To deploy on your VPS:"
echo "========================="
echo ""
echo "1. SSH to your VPS:"
echo "   ssh aj@your-vps-ip"
echo ""
echo "2. Navigate to project directory:"
echo "   cd /home/aj/pazar-plus"
echo ""
echo "3. Pull latest changes:"
echo "   git pull origin enhanced"
echo ""
echo "4. Restart the application:"
echo "   pm2 restart pazar-plus"
echo ""
echo "5. Monitor for Sequelize warnings:"
echo "   pm2 logs pazar-plus --lines 50 | grep -i sequelize"
echo ""
echo "6. Check overall application status:"
echo "   pm2 status"
echo "   pm2 logs pazar-plus --lines 20"
echo ""

echo "🔍 Verification steps:"
echo "====================="
echo ""
echo "1. Check that N11 orders process without warnings:"
echo "   pm2 logs pazar-plus | grep -A5 -B5 'totalDiscountAmount\\|agreedDeliveryDate'"
echo ""
echo "2. Verify Trendyol network errors are reduced:"
echo "   pm2 logs pazar-plus | grep -i 'trendyol.*error\\|trendyol.*retry'"
echo ""
echo "3. Confirm enum validation is working:"
echo "   pm2 logs pazar-plus | grep -i 'enum.*error\\|validation.*error'"
echo ""

echo "✅ Expected outcome:"
echo "==================="
echo ""
echo "• N11 Sequelize warnings about unknown attributes should be gone"
echo "• Trendyol should show fewer ECONNRESET errors"
echo "• All platform sync operations should work smoothly"
echo "• Production product creation should work without enum errors"
echo ""

echo "🆘 If you still see issues:"
echo "==========================="
echo ""
echo "1. Check the exact warning message:"
echo "   pm2 logs pazar-plus | grep -A2 -B2 'unknown.*attribute'"
echo ""
echo "2. Share the output for further debugging"
echo ""

echo "📝 Summary of fixes applied:"
echo "==========================="
echo "• Production enum values: user, platform_sync, platform, legacy"
echo "• N11 fields properly isolated to N11Order model only"
echo "• Trendyol retry logic with 5 attempts and exponential backoff"
echo "• Enhanced network error handling across all platform services"
echo ""

echo "🎯 Ready for deployment!"
