#!/bin/bash

echo "🔍 Render Environment Variables Checker"
echo "======================================="
echo ""
echo "📋 Copy these EXACT values to your Render dashboard:"
echo ""
echo "🔑 Core Variables:"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "JWT_SECRET=ooVu3Txg0gy0gD61udNBSOYe3ssuxlolXd6er/nesUA="
echo ""
echo "🗄️ Database:"
echo "DATABASE_URL=postgresql://neondb_owner:npg_Y2Jy0NswTRor@ep-aged-snow-a1fbqjnj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo "DB_TYPE=postgres"
echo ""
echo "⚙️ App Config:"
echo "API_VERSION=v1"
echo "CLIENT_URL=https://pazarplus.onrender.com"
echo "CORS_ORIGINS=https://pazarplus.onrender.com"
echo "JWT_EXPIRES_IN=7d"
echo ""
echo "🛡️ Security:"
echo "RATE_LIMIT_WINDOW_MS=900000"
echo "RATE_LIMIT_MAX_REQUESTS=100"
echo "LOG_LEVEL=info"
echo ""
echo "📍 Go to: https://dashboard.render.com"
echo "   → Click your backend service"
echo "   → Environment tab"
echo "   → Add each variable above"
echo "   → Save Changes"
echo ""
echo "🚀 After adding variables, Render will auto-redeploy!"
